import { TranscriptEvent, TranscriptParagraph } from '../types';

export class ReactiveTranscriptStore {
  private currentInterim: string = '';
  private finalSegments: TranscriptEvent[] = [];
  private groupedParagraphs: TranscriptParagraph[] = [];
  private listeners: (() => void)[] = [];

  // 4-second time window for grouping consecutive segments
  public readonly groupingWindowMs = 4000;

  public subscribe(cb: () => void): () => void {
    this.listeners.push(cb);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== cb);
    };
  }

  private notify() {
    this.listeners.forEach((cb) => cb());
  }

  public getInterim(): string {
    return this.currentInterim;
  }

  public getFinalSegments(): TranscriptEvent[] {
    return [...this.finalSegments];
  }

  public getParagraphs(): TranscriptParagraph[] {
    return [...this.groupedParagraphs];
  }

  public updateInterim(text: string) {
    this.currentInterim = text;
    this.notify();
  }

  public addFinal(event: TranscriptEvent) {
    if (!event.text || !event.text.trim()) return;

    this.currentInterim = '';
    const nowMs = event.timestampMs || Date.now();
    const cleanText = event.text.trim();
    const speaker = event.speaker || 'Candidate';

    const segmentWithMeta: TranscriptEvent = {
      ...event,
      text: cleanText,
      speaker,
      timestampMs: nowMs,
    };

    this.finalSegments.push(segmentWithMeta);

    // Grouping consecutive final segments
    const lastParagraph = this.groupedParagraphs[this.groupedParagraphs.length - 1];
    const isWithinWindow =
      lastParagraph &&
      nowMs - lastParagraph.timestampMs <= this.groupingWindowMs &&
      lastParagraph.speaker === speaker;

    if (isWithinWindow && lastParagraph) {
      // Append text cleanly with space
      const needsSpace = !lastParagraph.text.endsWith(' ') && !cleanText.startsWith(' ');
      lastParagraph.text += (needsSpace ? ' ' : '') + cleanText;
      lastParagraph.endTime = event.timestamp;
      lastParagraph.timestampMs = nowMs;
      lastParagraph.segments.push(segmentWithMeta);

      if (event.confidence !== undefined) {
        const confs = lastParagraph.segments
          .map((s) => s.confidence)
          .filter((c): c is number => typeof c === 'number');
        if (confs.length > 0) {
          lastParagraph.confidence = confs.reduce((a, b) => a + b, 0) / confs.length;
        }
      }
    } else {
      // Start a new readable paragraph block
      const newParagraph: TranscriptParagraph = {
        id: `p-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
        text: cleanText,
        speaker,
        startTime: event.timestamp,
        endTime: event.timestamp,
        timestampMs: nowMs,
        segments: [segmentWithMeta],
        confidence: event.confidence,
      };
      this.groupedParagraphs.push(newParagraph);
    }

    this.notify();
  }

  public clear() {
    this.currentInterim = '';
    this.finalSegments = [];
    this.groupedParagraphs = [];
    this.notify();
  }

  public formatTranscriptText(): string {
    const lines: string[] = [];
    lines.push('=======================================================');
    lines.push('         AI INTERVIEW ASSISTANT — SESSION TRANSCRIPT   ');
    lines.push('=======================================================');
    lines.push(`Session Date: ${new Date().toLocaleString()}`);
    lines.push(`Total Grouped Paragraphs: ${this.groupedParagraphs.length}`);
    lines.push(`Total Speech Segments: ${this.finalSegments.length}`);
    lines.push('-------------------------------------------------------');
    lines.push('');

    if (this.groupedParagraphs.length === 0) {
      lines.push('[No transcript recorded for this session]');
      return lines.join('\n');
    }

    this.groupedParagraphs.forEach((para, index) => {
      const timeSpan =
        para.startTime === para.endTime
          ? para.startTime
          : `${para.startTime} – ${para.endTime}`;

      lines.push(`[${timeSpan}] ${para.speaker}:`);
      lines.push(para.text);
      lines.push('');
    });

    lines.push('=======================================================');
    lines.push('Generated by AI Interview Assistant (.NET MAUI & Nova-3)');
    return lines.join('\n');
  }

  public downloadTranscript(customFileName?: string): boolean {
    if (this.finalSegments.length === 0 && this.groupedParagraphs.length === 0) {
      return false;
    }

    const content = this.formatTranscriptText();
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const now = new Date();
    const dateStamp = now.toISOString().slice(0, 10);
    const timeStamp = now.toTimeString().slice(0, 8).replace(/:/g, '-');
    const fileName = customFileName || `interview-transcript-${dateStamp}_${timeStamp}.txt`;

    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return true;
  }
}
